---

- block:
    - name: AWS_CLOUDMAP | Create '.aws' directory
      file:
        path: "{{ ansible_env.HOME }}/.aws"
        state: directory
        owner: "{{ ansible_user_id }}"
        mode: 0700

    - name: AWS_CLOUDMAP | Set credentials into '.aws/credentials' file
      blockinfile:
        path: "{{ ansible_env.HOME }}/.aws/credentials"
        block: |
          [{{ aws_cloudmap_profile }}]
          {{ 'aws_access_key_id = ' + aws_cloudmap_access_key_id if aws_cloudmap_access_key_id is defined else '' }}
          {{ 'aws_secret_access_key = ' + aws_cloudmap_secret_access_key if aws_cloudmap_secret_access_key is defined else '' }}
          {{ 'aws_session_token = ' + aws_cloudmap_session_token if aws_cloudmap_session_token is defined else '' }}
        create: true
        owner: "{{ ansible_user_id }}"
        mode: 0600
  when:
    - aws_cloudmap_profile is defined
    - aws_cloudmap_set_credentials is defined
    - aws_cloudmap_set_credentials
  tags: aws_cloudmap_configure_credentials
