---

- block:
    - name: AWS_CLOUDMAP | Check if 'aws-cli' is installed
      command: "aws --version"
      register: aws_cli_check
      changed_when: false
      check_mode: false
      tags:
        - aws_cloudmap_check_cli
  rescue:
    - name: AWS_CLOUDMAP | Error
      ansible.builtin.fail:
        msg: "ERROR: aws-cli is not installed. Please, install it before running this role."

- name: AWS_CLOUDMAP | AWS region to be used
  debug:
    msg: "AWS region '{{ aws_cloudmap_region }}' will be used"
  when: aws_cloudmap_region is defined
  tags:
    - aws_cloudmap_check_cli
    - aws_cloudmap_show_region
