---

- name: Prepare
  hosts: aws_cloudmap_group
  gather_facts: true
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Prepare | Download aws-cli
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_facts.architecture }}.zip"
        dest: /root/awscliv2.zip
        owner: root
        group: root
        mode: 0640

    - name: Prepare | Unzip aws-cli
      unarchive:
        src: /root/awscliv2.zip
        remote_src: yes
        dest: /root/
        owner: root
        group: root

    - name: Prepare | Install aws-cli
      command: "/root/aws/install --bin-dir {{ aws_cloudmap_bin_path }} --update"
      args:
        creates: "{{ aws_cloudmap_bin_path }}/{{ aws_cloudmap_exec_name }}"
